#page title
page_title                                : Patropy - Personal Wallpapers                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
#ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

#appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.patropy.patropy                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Patropy - Personal Wallpapers                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
#app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Create stunning wallpapers with just a few clicks.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : modulovalue
#your_link                                 :
#your_city                                 : Copenhagen
email_address                             : mod-val@web.de
#facebook_username                         :
#instagram_username                        : ebaehr
#twitter_username                          : ebaehr
#github_username                           : emilbaehr
#youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Easy to use
    description                           : Create stunning wallpapers with just a few clicks.
    fontawesome_icon_name                 : magic
    
  - title                                 : Customization Options
    description                           : You can customize each wallpaper to fit your taste.
    fontawesome_icon_name                 : mobile

  - title                                 : Find Inspiration
    description                           : Or let Patropy create wallpapers for you and you may find the inspiration you've been looking for.
    fontawesome_icon_name                 : star

#  - title                                 : Automatic Icon and Metadata
#    description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
#    fontawesome_icon_name                 : sync
#
#  - title                                 : Easy to Tweak
#    description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
#    fontawesome_icon_name                 : adjust
#
#  - title                                 : Feature List
#    description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
#    fontawesome_icon_name                 : star
#
#  - title                                 : Smart App Banner
#    description                           : Display a smart app banner on iOS devices.
#    fontawesome_icon_name                 : arrow-alt-circle-down
#
#  - title                                 : Social Links
#    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
#    fontawesome_icon_name                 : link
#
#  - title                                 : FontAwesome Support
#    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
#    fontawesome_icon_name                 : info-circle
#
#  - title                                 : # New Feature Title
#    description                           : # New Feature Description
#    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#262b2d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#FF0000"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
